cloud:
  aws:
    credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ru-central1
      auto: false

application:
  bucket:
    name: best-site


server:
  port: 8080